name: Keep Server Active

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  ping_job:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to keep server active
        run: |
          curl -I https://getyourtutorsl.com || echo "Request failed"
